name: Slither Analysis
on: [push, pull_request]
jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Cache node modules
      uses: actions/cache@v2
      env:
       cache-name: cache-node-modules
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      run: yarn install

    - name: Hardhat compile
      run: yarn compile

    - name: Hacky solution
      run: cp -r generated/artifacts .

    - name: Run Slither
      uses: crytic/slither-action@v0.1.1
      continue-on-error: true
      id: slither
      with:
        node-version: 16
        sarif: results.sarif
        ignore-compile: true

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}